//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Common {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class ProductSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ProductSettings defaultInstance = ((ProductSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ProductSettings())));
        
        public static ProductSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// The product name.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The product name.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UWF7dk94Zlp2GkxvVlFBelZzTGNZPBU+")]
        public string Component {
            get {
                return ((string)(this["Component"]));
            }
        }
        
        /// <summary>
        /// The version of the product, which can be different from that of the assemblies.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The version of the product, which can be different from that of the assemblies.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NConPRIdAgw=")]
        public string Version {
            get {
                return ((string)(this["Version"]));
            }
        }
        
        /// <summary>
        /// Product version suffix (e.g. SP1).
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Product version suffix (e.g. SP1).")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LwQXEyIdAgw=")]
        public string VersionSuffix {
            get {
                return ((string)(this["VersionSuffix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UWF7dk94Zlp2MBsAJDoyDg==")]
        public string Product {
            get {
                return ((string)(this["Product"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Edition {
            get {
                return ((string)(this["Edition"]));
            }
        }
        
        /// <summary>
        /// Product copyright.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Product copyright.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RmtnalB0ZWRMGikwFQ8SWlJrQGFSWENwFUJLcRUPUnVpKmVmYkt0bAJIcHNdb3ppQDMlAjcgMgA=")]
        public string Copyright {
            get {
                return ((string)(this["Copyright"]));
            }
        }
        
        /// <summary>
        /// Product license.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Product license.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RmtnalB0ZWRMGjNjDRoAPgY0CSx0UHBfR0t5XE1OYDlMZHQhD2JscwJIfGdQaX8sVnhWZ0VWV2QZGwIyN" +
            "S8PPg==")]
        public string License {
            get {
                return ((string)(this["License"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L0ZyZ0MdAgw=")]
        public string Release {
            get {
                return ((string)(this["Release"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Name {
            get {
                return ((string)(this["Name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FamilyName {
            get {
                return ((string)(this["FamilyName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SubComponent {
            get {
                return ((string)(this["SubComponent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MzEmJxEdAgw=")]
        public string Password1 {
            get {
                return ((string)(this["Password1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nj0mKxMdAgw=")]
        public string Password2 {
            get {
                return ((string)(this["Password2"]));
            }
        }
    }
}
